### ISSUE TITLE
看起来跟solid没区别，为啥要重复造轮子

### ISSUE THREAD

**Issue by a554878526** [viewfly/viewfly#10]

**Comment by viewfly** [comment]
就像你的问题一样，只是看起来像，实现原理是完全不一样的。
Viewfly 的 API 会比 Solid 简单很多，并且 Viewfly 也没有自造的语法，所以也不依赖于特定的编译器。我们想做一个不需要很复杂的配置，也无需太多记忆，使用起来符合直觉，没有数据污染的前端视图库（或者说框架）。
从创建组件的成本来说：
1、React应该是最自由、最简单的，但 React Hooks 的闭包陷阱引入了很大的复杂度，开发者往往要非常小心，才能写出健壮的代码。
2、Vue 的单文件组件也较简单，但 .vue 文件不是能个通用的文件，不能很好的与 ts/js 交互，需要 vue 的编译器，也导致 Vue 需要 defineProps、defineEmits 等特殊的 API，而不能简单的使用 interface 实现。同时，Vue 对原数据的劫持，导致在一些对第三方大对象实现视图自动更新的场景中变得难以实现。Vue 也导致了数据污染，往一个被 reactive 包装过的对象写入一个对象，再取出来，由于被 Vue 包装，和原对象将不相等，也不能使用 instanceof 判断类型。这导致了额外的复杂度。虽然 Vue 也提供了解包的 API 和 shallowReactive，但这并不能完全解决上述问题。
3、Angular 没有上述问题，但 Angular 样板代码太多，概念多，工程庞大，上手成本对大多数人来说，是很高的。
4、Solid 和 Selvet 均走的是编译器路线，这将导致前端产生更多的方言和特定环境下才有效的实践。当下，我们不是太赞成这种方式。
希望我的回答能帮助到你。
