### ISSUE TITLE
useSignal使用一点问题

### ISSUE THREAD

**Issue by sprint-zhang** [viewfly/viewfly#13]
在组件中使用 useSignal  获取到的值。若没有用于return的element中。则组件不会刷新。
那若我只是用 useSignal  获取的值用于组件内的计算，但我又需要依赖此值更新计算。这样当前能实现吗

**Comment by sprint-zhang** [comment]
同时大佬很想看你收集依赖部分的代码，能指引下目录吗，

**Comment by textbus** [comment]
可以看一下 useEffect 和 useDerived，应该可以满足你的需求。
