### ISSUE TITLE
支持 hidden, checked 这类特殊属性

### ISSUE THREAD

**Issue by faxinwang** [viewfly/viewfly#14]
hidden, checked 这类属性是通过属性是否在html标签中存在与否来控制原生dom元素的状态的，不能直接把true/false 渲染成字符串。

**Comment by viewfly** [comment]
已修复：
 - @viewfly/core@0.2.3
 - @viewfly/hooks@0.2.3
 - @viewfly/platform-browser@0.2.3
 - @viewfly/router@0.2.3
 - @viewfly/scoped-css@0.2.3
