### ISSUE TITLE
[讨论] 方法组件的方法必须返回一个函数吗？

### ISSUE THREAD

**Issue by zbysir** [viewfly/viewfly#15]
尝试运行了下，包括示例都写了必须返回一个函数。

```javascript
const count = createSignal(0)

function App() {
  return () => <div>{count()}</div>
}
```

而在 react 或者其他使用 jsx 的框架中，似乎不存在这个限制，他们的写法会更简单。

```javascript
function App() {
  return "hi"
}
```

后者在 viewfly 中会报错：

```
TypeError: this.instance.$render is not a function
    at Component.render (VM7905 4cad1cd3-d882-4d60-9604-9fd4f54ea220:732:40)
    at componentRender (VM7905 4cad1cd3-d882-4d60-9604-9fd4f54ea220:1573:48)
    at buildView (VM7905 4cad1cd3-d882-4d60-9604-9fd4f54ea220:1318:9)
    at buildView (VM7905 4cad1cd3-d882-4d60-9604-9fd4f54ea220:1341:17)
```

能否做下兼容两种写法呢？我胡乱的猜测应该是可以的，因为 App 自己本身就是一个函数了。

> btw 这个库好棒，语法很简单爱看，我想尝试在 viewfly 的语法基础上用 go 来做 SSR。

**Comment by zbysir** [comment]
```
import { createSignal } from '@viewfly/core'
import { createApp } from '@viewfly/platform-browser'

const count = createSignal(0)

function App() {
  const count2 = count() + 2;

  return () => (
    <div>
      <div>{count()}</div>
      <div>{count2}</div>
      <button onClick={() => {
          count.set(count() + 1)
      }}>click me</button>
    </div>
  )
}

createApp(<App/>).mount(document.getElementById('app'))

```

在这里例子中，count2 不会响应改变，这和 react 的运行方式不一样，viewfly 就是通过不重新执行整个方法组件，而只重新执行 return 的函数来 “避免闭包陷阱” 的吧。

按这个实现原理，那确实返回一个函数是必须的，我猜测对吧？

**Comment by textbus** [comment]
> ```
> import { createSignal } from '@viewfly/core'
> import { createApp } from '@viewfly/platform-browser'
> 
> const count = createSignal(0)
> 
> function App() {
>   const count2 = count() + 2;
> 
>   return () => (
>     <div>
>       <div>{count()}</div>
>       <div>{count2}</div>
>       <button onClick={() => {
>           count.set(count() + 1)
>       }}>click me</button>
>     </div>
>   )
> }
> 
> createApp(<App/>).mount(document.getElementById('app'))
> ```
> 
> 在这里例子中，count2 不会响应改变，这和 react 的运行方式不一样，viewfly 就是通过不重新执行整个方法组件，而只重新执行 return 的函数来 “避免闭包陷阱” 的吧。
> 
> 按这个实现原理，那确实返回一个函数是必须的，我猜测对吧？

你说的是正确的，react 只是看起来简单，用起来可不简单。

**Comment by zbysir** [comment]
@textbus 好的。好奇 [viewfly](https://github.com/viewfly/viewfly) 和 [textbus](https://github.com/textbus/textbus) 背后的团队，挺厉害的，是个人项目？

**Comment by textbus** [comment]
> @textbus 好的。好奇 [viewfly](https://github.com/viewfly/viewfly) 和 [textbus](https://github.com/textbus/textbus) 背后的团队，挺厉害的，是个人项目？

业余时间的一些个人兴趣，愿意的话，你也可以来参加
