### ISSUE TITLE
从简单和开发直觉的角度，有几个疑问请教

### ISSUE THREAD

**Issue by T-Macgrady** [viewfly/viewfly#9]
1、<div>{number()}</div>； number.set(number() + 1) 有点违反开发直觉？useState那种实现有啥不妥
2、数据透传依赖注入实现能不能用装饰器简洁些？
3、常用的hook，类似useMemo或者useWatch有对应实现吗

**Comment by viewfly** [comment]
你好。回答你的问题：
1、我没说错的话，你是指 react 的 useState 吧，react 的问题主要是闭包陷阱，每次渲染会重新执行组件本身，如果程序复杂，手动管理依赖是很容易出错的，导致你访问的 state 是上一次，或更前面设置的值，这也是当前 react 面临的最大问题，即幽灵闭包。简单的业务，写起来很容易。一旦依赖关系复杂，再加上异步逻辑，这将变得更复杂。
为什么没采用类似 vue 的 proxy，这是因为 proxy 会导致设置进去的对象再取出来，两个不是同一个引用，这在复杂业务中，是很容易出错的，不能用 === 运算符判断相等，也不能用 instanceof，虽然 vue 也提供了相应的解包 api，但当我们即需要视图实现动态响应，又不想 vue 去修改我们的对象时，这将使开发变得困难。
而 Signal 这种形式，可以保证不会修改原始值，也不会有闭包陷阱。当然，写法上感觉要麻烦一点，但我们认为，这种取舍是值得的。同时，你会在更多的前端框架中见到 Signal 的身影。
2、我不明白你要想要装饰器，还是说不要装饰器。我就以目前的设计来解释一下吧。viewfly 目前的设计，是可以完全不用装饰器的，provide 接口 本身支持 useValue/useFactory，当然，也完全可以用装饰器在 class 中实现依赖注入。
没有用字符串做 key，主要是为了类型校验安全。且目前这种实现已有 Angular /nestjs 等一系列框架的实践证明，更容易写出架构合理代码。虽然目前国内大多数前端都在用 vue/react 开发，但应该没人否认 Angular 在架构设计上的先进性。
3、memo 的 api 我们正在考虑需不需要，如果可能，我们不希望开放更多的 api，而是在框架层面直接做到，不把这种复杂性抛给开发者。watch 其实现在对应的是 useEffect 和 useDerived，这个已有 API，不完全一样，但也差不多。

最后，viewfly 的目标是，尽量少的 api，尽量少的心智负担，并尽全力不引入特殊语法或编译环境依赖。让更多的人，只在简单掌握 js 和 jsx 的基础上，即可以写出健壮、易维护、易测试的代码。
希望我们回答能帮助到你，谢谢！
